global:
  scrape_interval: 15s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'scrapper_monitoring'

    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: [ 'host.docker.internal:9081' ]

  - job_name: 'bot_monitoring'

    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: [ 'host.docker.internal:9080' ]
