/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.entity.jooq;


import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.tinkoff.edu.java.scrapper.entity.jooq.tables.Chat;
import ru.tinkoff.edu.java.scrapper.entity.jooq.tables.Link;
import ru.tinkoff.edu.java.scrapper.entity.jooq.tables.Subscription;
import ru.tinkoff.edu.java.scrapper.entity.jooq.tables.records.ChatRecord;
import ru.tinkoff.edu.java.scrapper.entity.jooq.tables.records.LinkRecord;
import ru.tinkoff.edu.java.scrapper.entity.jooq.tables.records.SubscriptionRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CONSTRAINT_1 = Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1"), new TableField[] { Chat.CHAT.ID }, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_2 = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[] { Link.LINK.ID }, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_23 = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_23"), new TableField[] { Link.LINK.URL }, true);
    public static final UniqueKey<SubscriptionRecord> CONSTRAINT_9E7 = Internal.createUniqueKey(Subscription.SUBSCRIPTION, DSL.name("CONSTRAINT_9E7"), new TableField[] { Subscription.SUBSCRIPTION.CHAT_ID, Subscription.SUBSCRIPTION.LINK_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<SubscriptionRecord, ChatRecord> CONSTRAINT_9 = Internal.createForeignKey(Subscription.SUBSCRIPTION, DSL.name("CONSTRAINT_9"), new TableField[] { Subscription.SUBSCRIPTION.CHAT_ID }, Keys.CONSTRAINT_1, new TableField[] { Chat.CHAT.ID }, true);
    public static final ForeignKey<SubscriptionRecord, LinkRecord> CONSTRAINT_9E = Internal.createForeignKey(Subscription.SUBSCRIPTION, DSL.name("CONSTRAINT_9E"), new TableField[] { Subscription.SUBSCRIPTION.LINK_ID }, Keys.CONSTRAINT_2, new TableField[] { Link.LINK.ID }, true);
}
