app:
  test: "i will work in Tinkoff(scrapper)"
  linkCheckPeriodMinutes: 20
  clients:
    stackoverflow: "https://api.stackexchange.com/2.3"
    github: "https://api.github.com"
    bot: "http://127.0.0.1:8080"
  scheduler:
    interval: 15000
  databaseAccessType: jdbc
  queueName: scrapperQueue
  exchangeName: scrapperExchange
  useQueue: true

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username:
    password:
    driverClassName: org.postgresql.Driver
  application:
    name: scrapper

management:
  server:
    port: 9081
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      path-mapping:
        prometheus: /metrics
      exposure:
        include: health,info,prometheus
      base-path: /
  metrics:
    tags:
      application: ${spring.application.name}
