app:
  test: "i will work in Tinkoff(scrapper)"
  stackoverflow: "https://api.stackexchange.com/2.3"
  github: "https://api.github.com"
  scheduler:
    interval: 7500

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui