app:
  test: "i will work in Tinkoff(bot)"
  scrapper:
    url: "http://127.0.0.1:8081"
  bot:
    token:
  queueName: scrapperQueue
  exchangeName: scrapperExchange

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 1
  application:
    name: bot

management:
  server:
    port: 9080
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      path-mapping:
        prometheus: /metrics
      exposure:
        include: health,info,prometheus
      base-path: /
  metrics:
    tags:
      application: ${spring.application.name}
