name: Build bot

on:
  push:
    paths:
      - 'bot/**'
      - 'common-dto/**'
      - 'link-parser/**'
      - 'pom.xml'
      - '.github/workflows/bot.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bot

jobs:
  build:
    runs-on: ubuntu-22.04
    needs: checkstyle
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
      - name: Build bot app
        run: mvn package -pl bot -am
      - id: string
        name: String cases
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.actor }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ steps.string.outputs.lowercase }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image bot
        run: docker build -f bot.Dockerfile -t ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}/${{ env.IMAGE_NAME }}:latest .
      - name: Push Docker image bot
        run: docker push ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}/${{ env.IMAGE_NAME }}:latest
  checkstyle:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
      - name: Run Checkstyle
        run: mvn -pl bot -am checkstyle:check
