name: Build scrapper

on:
  push:
    paths:
      - 'scrapper/**'
      - 'migrations/**'
      - 'common-dto/**'
      - 'link-parser/**'
      - 'pom.xml'
      - '.github/workflows/scrapper.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: scrapper

jobs:
  build:
    runs-on: ubuntu-22.04
    needs: checkstyle
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
      - name: Build scrapper app
        run: mvn package -pl scrapper -am
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image scrapper
        run: docker build -f scrapper.Dockerfile -t ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest .
      - name: Push Docker image scrapper
        run: docker push ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
  checkstyle:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
      - name: Run Checkstyle
        run: mvn -pl scrapper -am checkstyle:check
